# Generated by Django 4.2.6 on 2024-07-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bigint_f", models.BigIntegerField()),
                ("bool_f", models.BooleanField()),
                ("date_f", models.DateField(auto_now=True)),
                ("char_f", models.CharField(max_length=20, unique=True)),
                ("datetime_f", models.DateTimeField(auto_now_add=True)),
                ("decaimal_f", models.FloatField(null=True)),
                ("float_f", models.FloatField(null=True)),
                ("int_f", models.IntegerField(default=2010)),
                ("text_f", models.TextField()),
            ],
        ),
    ]
